name: mitra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  mongo_dart: ^0.9.2
  fl_chart: ^0.63.0
  intl: ^0.18.1
  http: ^0.13.6
  flutter_gemini: ^3.0.0
  speech_to_text: ^6.6.0
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  path: ^1.9.0
  table_calendar: ^3.0.9
  google_fonts:
  logger: ^2.0.2+1
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/anxiety.jpg
    - assets/session.jpg
    - assets/lottie/
